[tool.poetry]
name = "pytest_container"
version = "0.0.1"
description = "Pytest fixtures for writing container based tests"
authors = ["Dan Čermák <dcermak@suse.com>"]
license = "GPLv2.0"

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"
pytest = ">= 3.10"
pytest-testinfra = ">=6.4.0"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
mypy = "^0.910"
pylint = "^2.10.2"
reorder-python-imports = "^2.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
