---
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  format:
    name: Ensure code is properly formatted
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}

      - run: |
          pip install --upgrade poetry
          poetry install
          poetry run ./format.sh --check

  ci:
    name: Run the integration tests
    runs-on: ${{ matrix.os_version }}
    strategy:
      fail-fast: false
      matrix:
        os_version: ["ubuntu-latest"]
        python_version: ["3.7", "3.8", "3.9", "3.10"]
        container_runtime: ["podman", "docker"]
        include:
          - os_version: "ubuntu-20.04"
            python_version: "3.6"
            container_runtime: "podman"
          - os_version: "ubuntu-20.04"
            python_version: "3.6"
            container_runtime: "docker"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - uses: actions/cache@v3
        with:
          path: ~/.tox
          key: tox-${{ matrix.python_version }}-${{ hashFiles('poetry.lock') }}

      - run: pip install --upgrade 'tox<4' poetry
        if: (matrix.python_version == '3.6') || (matrix.python_version == '3.7')

      - run: pip install --upgrade tox poetry
        if: (matrix.python_version == '3.8') || (matrix.python_version == '3.9') || (matrix.python_version == '3.10')

      - run: |
          export CUR_USER="$(whoami)"
          sudo loginctl enable-linger ${CUR_USER}

      - name: patch tox.ini for old poetry versions shipped with python 3.6 & 3.7 and remove the lockfile
        if: (matrix.python_version == '3.6') || (matrix.python_version == '3.7')
        run: |
          sed -i 's| --no-root --sync|\nskip_install = true|' tox.ini
          rm poetry.lock

      - run: |
          mkdir ./tmp/
          chmod 1777 ./tmp
          export TMPDIR="$(pwd)/tmp"
          tox -e py${PY_VER//\./} -- -n auto --reruns 3 --pytest-container-log-level DEBUG
          tox -e py${PY_VER//\./} -- --reruns 3 --pytest-container-log-level DEBUG
        env:
          CONTAINER_RUNTIME: ${{ matrix.container_runtime }}
          PY_VER: ${{ matrix.python_version }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

  build:
    name: Build the package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}

      - name: Run the build
        run: |
          pip install --upgrade poetry
          poetry install
          poetry build

      - uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/pytest_container*whl
          if-no-files-found: error

  install:
    name: Install the package
    runs-on: ${{ matrix.os_version }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os_version: ["ubuntu-latest"]
        python_version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os_version: "ubuntu-20.04"
            python_version: "3.6"

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - uses: actions/download-artifact@v3
        with:
          name: wheel
          path: dist

      - name: install the wheel
        run: pip install --user dist/pytest_container*whl

      - name: run a smoke test that the package has been installed
        run: python -c "import pytest_container; print (pytest_container.__name__)"

  documentation:
    name: Build the documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/cache@v3
        with:
          path: ~/.tox
          key: tox-${{ hashFiles('poetry.lock') }}

      - run: pip install --upgrade tox poetry

      - run: 'tox -e doc'

  lint:
    name: Lint the source code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/cache@v3
        with:
          path: ~/.tox
          key: tox-${{ hashFiles('poetry.lock') }}

      - run: pip install --upgrade tox poetry

      - run: 'tox -e lint'
